pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: gradle
    image: eclipse-temurin:21-jdk-noble
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "500m"
    command:
    - sleep
    args:
    - infinity
'''
            defaultContainer 'gradle'
        }
    }
    stages {
        stage('Build') {
            steps {
                timestamps {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/spring-projects/spring-framework.git']])

                    readCache 'gradle-cache'

                    sh """
                    ./gradlew --no-scan --gradle-user-home=.gradle-home -x test :spring-core:build
                    """
        
                    writeCache includes: '.gradle-home/**,gradle/**', name: 'gradle-cache'
                }
            }
        }
    }
}
