pipeline {
  agent none
  stages {
    stage('maven') {
      agent {
        node {
          label 'maven'
        }

      }
      steps {
        echo 'maven Stage'
      }
    }
    stage('nodejs') {
      agent {
        node {
          label 'nodejs-app'
        }

      }
      steps {
        echo 'nodejs Stage'
      }
    }
    stage('python') {
      agent {
        node {
          label 'python'
        }

      }
      steps {
        echo 'python Stage'
      }
    }
    stage('gradle') {
      agent {
        node {
          label 'gradle'
        }

      }
      steps {
        echo 'gradle Stage'
      }
    }
    stage('dotnet') {
      agent {
        node {
          label 'dotnet'
        }

      }
      steps {
        container('dotnet') {
            sh 'dotnet --version'
            echo 'dotnet Stage'
        }
    }
    }
  }
}
