pipeline {
  agent none
  stages {
    stage('Build') {
      agent {
        node {
          label 'maven'
        }

      }
      steps {
        echo 'Build Stage'
      }
    }
    stage('Dev') {
      agent {
        node {
          label 'nodejs-app'
        }

      }
      steps {
        echo 'Dev Stage'
      }
    }
    stage('Test') {
      agent {
        node {
          label 'nodejs-app'
        }

      }
      steps {
        echo 'Test Stage'
      }
    }
    stage('Prod') {
      agent {
        node {
          label 'nodejs-app'
        }

      }
      steps {
        echo 'Prod Stage'
      }
    }
  }
}
