pipeline {
  agent none
  stages {
    stage('maven') {
      agent {
        node {
          label 'maven'
        }

      }
      steps {
        container('maven') {
        sh 'mvn -v'
        echo 'maven Stage'
        }
      }
    }
    stage('nodejs') {
      agent {
        node {
          label 'nodejs-app'
        }

      }
      steps {
        container('nodejs') {
        sh 'node --version'
        echo 'nodejs Stage'
        }
      }
    }
    stage('python') {
      agent {
        node {
          label 'python'
        }

      }
      steps {
        container('python') {
        sh 'python --version'
        echo 'python Stage'
        }
      }
    }
    stage('gradle') {
      agent {
        node {
          label 'gradle'
        }

      }
      steps {
        container('gradle') {
          sh 'gradle --version'
          echo 'gradle Stage'
        }
      }
    }
    stage('dotnet') {
      agent {
        node {
          label 'dotnet'
        }

      }
      steps {
        container('dotnet') {
            sh 'dotnet --version'
            echo 'dotnet Stage'
        }
    }
    }
  }
}
